<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\Common\" />
    <Folder Include="Application\Usecases\" />
    <Folder Include="Domain\Abstractions\" />
    <Folder Include="Infrastructure\Repositories\" />
    <Folder Include="Infrastructure\Persistance\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Common\ECommerce.Common.csproj" />
  </ItemGroup>

</Project>
